package pro.fazeclan.river.stupid_express.role.amnesiac;

import dev.doctor4t.trainmurdermystery.api.Role;
import dev.doctor4t.trainmurdermystery.api.TMMRoles;
import dev.doctor4t.trainmurdermystery.cca.GameWorldComponent;
import dev.doctor4t.trainmurdermystery.cca.PlayerShopComponent;
import dev.doctor4t.trainmurdermystery.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.trainmurdermystery.entity.PlayerBodyEntity;
import dev.doctor4t.trainmurdermystery.index.TMMItems;
import dev.doctor4t.trainmurdermystery.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.event.player.UseEntityCallback;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.InteractionResult;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import pro.fazeclan.river.stupid_express.constants.SERoles;

public class RoleSelectionHandler {

    private static void clearAllKnives(ServerPlayer player) {
        for (int i = 0; i < player.getInventory().getContainerSize(); i++) {
            if (player.getInventory().getItem(i).is(TMMItems.KNIFE)) {
                player.getInventory().setItem(i, net.minecraft.world.item.ItemStack.EMPTY);
            }
        }
    }

    public static void init() {
        UseEntityCallback.EVENT.register(((player, level, interactionHand, entity, entityHitResult) -> {
            if (!(player instanceof ServerPlayer interacting)) {
                return InteractionResult.PASS;
            }
            if (!interacting.gameMode.isSurvival()) {
                return InteractionResult.PASS;
            }
            GameWorldComponent gameWorldComponent = GameWorldComponent.KEY.get(player.level());
            if (!gameWorldComponent.isRole(player, SERoles.AMNESIAC)) {
                return InteractionResult.PASS;
            }
            if (!(entity instanceof PlayerBodyEntity victim)) {
                return InteractionResult.PASS;
            }
            Role role = gameWorldComponent.getRole(victim.getPlayerUuid());

            // 清除物品栏中的所有刀
            clearAllKnives(player);

            PlayerShopComponent playerShopComponent = PlayerShopComponent.KEY.get(player);

            gameWorldComponent.addRole(player, role);
            ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, role);
            playerShopComponent.setBalance(200);
            if (Harpymodloader.VANNILA_ROLES.contains(role)) {
                if (role.equals(TMMRoles.VIGILANTE)) {
                    player.addItem(TMMItems.REVOLVER.getDefaultInstance());
                }
                ServerPlayNetworking.send(
                        interacting,
                        new AnnounceWelcomePayload(
                                RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(
                                        role.equals(TMMRoles.VIGILANTE) ? RoleAnnouncementTexts.VIGILANTE :
                                                role.equals(TMMRoles.KILLER) ? RoleAnnouncementTexts.KILLER :
                                        RoleAnnouncementTexts.CIVILIAN),
                                gameWorldComponent.getAllKillerTeamPlayers().size(),
                                0
                        )
                );
            } else {
                ServerPlayNetworking.send(
                        interacting,
                        new AnnounceWelcomePayload(
                                RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(role)),
                                gameWorldComponent.getAllKillerTeamPlayers().size(),
                                0
                        )
                );
            }

            return InteractionResult.CONSUME;
        }));
    }

}